Sc 48 crud
AGMS-Rocksters/social_club pull request #22
Opened 2024-09-06 11:56 UTC by ArezouRa

## What type of PR is this? (check all applicable)

- [ ] Refactor
- [X] Feature
- [ ] Bug Fix
- [ ] Optimization
- [ ] Documentation Update

## Description
CRUD operations and tests for messages and Communication

## Related Tickets & Documents

- Related Issue #
- Closes #

## Added/updated tests?

_It is encouraged to keep the code coverage percentage at 80% and above._

- [X] Yes
- [ ] No, and this is why: _please replace this line with details on why tests
      have not been included_
- [ ] I need help with writing tests

## [optional] What gif best describes this PR or how it makes you feel?

![alt_text](gif_link)

2024-09-09 13:07 UTC, nomisreual requested changes
One missing field in models.

Messages and communication access should be restricted.

2024-09-09 13:07 UTC, nomisreual commented on src/messaging/views.py
> +
only fetch communications of current user

2024-09-09 13:07 UTC, nomisreual commented on src/messaging/views.py
> +    serializer_class = CommunicationSerializer
again only for currently authenticated user

2024-09-10 13:52 UTC, ArezouRa commented on src/messaging/views.py
> +    serializer_class = MessageSerializer
tried that. would be glad to have your review

2024-09-10 13:52 UTC, ArezouRa commented on src/messaging/models.py
> +    msg = models.TextField()
is added and is waiting for review

2024-09-10 13:52 UTC, ArezouRa commented on src/messaging/views.py
> +    serializer_class = MessageSerializer
tried to implement. hope that's what you wanted

2024-09-17 08:31 UTC, nomisreual requested changes

2024-09-17 08:31 UTC, nomisreual commented on src/messaging/serializers.py
> +    )
so this grabs all messages authored by the current user?

2024-09-17 08:31 UTC, nomisreual commented on src/messaging/views.py
> +        ) | Message.objects.filter(communication__to_user=self.request.user)
That does only filter for messages for which the current user is part of a communication. Looks like it's listing all messages though, not specific to one communication.

2024-09-17 08:31 UTC, nomisreual commented on src/messaging/views.py
> +    serializer_class = MessageSerializer
see comment below

2024-09-17 08:31 UTC, nomisreual commented on src/messaging/views.py
> +    serializer_class = MessageSerializer
looks good i think

2024-09-17 08:31 UTC, nomisreual commented on src/messaging/views.py
> +
looks good.

2024-09-17 08:31 UTC, nomisreual commented on src/messaging/urls.py
> +    path("messages/", MessageList.as_view(), name="message-list"),
maybe include the communication ID, so it is easier to fetch a list of messages related to one communication

2024-09-17 09:45 UTC, ArezouRa commented on src/messaging/views.py
> +        ) | Message.objects.filter(communication__to_user=self.request.user)
it's changed to get messages in a specific communication now :)

2024-09-17 10:06 UTC, nomisreual approved these changes
loioks good now

2024-09-17 11:57 UTC, merged